FROM node:18-alpine as build

WORKDIR /client

COPY ./client/package*.json ./

RUN yarn install

COPY ./client .

RUN yarn add react-scripts

RUN yarn build

FROM nginx:alpine

COPY --from=build ./client/build /usr/share/nginx/html

COPY nginx.conf.template /etc/nginx/nginx.conf.template

EXPOSE 80 443

CMD cp /etc/nginx/nginx.conf.template /etc/nginx/nginx.conf && nginx -g 'daemon off;'
