FROM node:18-alpine as build

WORKDIR /client

COPY ./client/package*.json ./

RUN yarn install

COPY ./client .

ARG DOMAIN

RUN yarn build

FROM nginx:alpine

COPY --from=build ./client/build /usr/share/nginx/html

COPY ./ssl/* /etc/nginx/

COPY nginx.conf.template /etc/nginx/nginx.conf.template

EXPOSE 80 443

CMD envsubst '$DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'